#!/usr/local/bin/php
<?php

declare(strict_types=1);

use Chemaclass\FinanceYahoo\Company\CompanyCrawlerFactory;
use Chemaclass\FinanceYahoo\Crawler\RootAppJsonCrawler;
use Chemaclass\FinanceYahoo\FinanceYahooConfig;
use Chemaclass\FinanceYahoo\FinanceYahooFacade;
use Symfony\Component\HttpClient\HttpClient;

require_once dirname(__DIR__) . '/vendor/autoload.php';

Dotenv\Dotenv::createImmutable(__DIR__)->load();

$facade = new FinanceYahooFacade(
    new FinanceYahooConfig($_ENV['TICKERS']),
    new CompanyCrawlerFactory(HttpClient::create())
);

$jsonExtractor = new RootAppJsonCrawler(
    fn (array $json): array => [
        'name' => $json['context']['dispatcher']['stores']['QuoteSummaryStore']['price']['shortName'],
        'price' => $json['context']['dispatcher']['stores']['QuoteSummaryStore']['financialData']['targetLowPrice']['fmt'],
        'recommendationTrend' => $json['context']['dispatcher']['stores']['QuoteSummaryStore']['recommendationTrend']['trend']['0'],
    ]
);

$companies = $facade->crawlStock($jsonExtractor);

dump($companies);
