#!/usr/local/bin/php
<?php

declare(strict_types=1);

use Chemaclass\FinanceYahoo\Company\CompanyCrawlerFactory;
use Chemaclass\FinanceYahoo\Crawler\HtmlCrawler\Analysis;
use Chemaclass\FinanceYahoo\Crawler\HtmlCrawler\Summary;
use Chemaclass\FinanceYahoo\Crawler\HtmlSiteCrawler;
use Chemaclass\FinanceYahoo\Crawler\RootAppJsonCrawler;
use Chemaclass\FinanceYahoo\FinanceYahooConfig;
use Chemaclass\FinanceYahoo\FinanceYahooFacade;
use Symfony\Component\HttpClient\HttpClient;

require_once dirname(__DIR__) . '/vendor/autoload.php';

Dotenv\Dotenv::createImmutable(__DIR__)->load();

$siteCrawlers = [
    new HtmlSiteCrawler(
        'https://finance.yahoo.com/quote/%s/summary',
        [
            'CompanyFullName' => new Summary\CompanyFullNameCrawler(),
            'EstimateReturn' => new Summary\EstimateReturnCrawler(),
        ]
    ),
    new HtmlSiteCrawler(
        'https://finance.yahoo.com/quote/%s/analysis',
        [
            'EarningsEstimate' => new Analysis\EarningsEstimateCrawler(),
        ]
    ),
    new RootAppJsonCrawler(
        'https://finance.yahoo.com/quote/%s',
        fn (array $json): array => [
            'RawPrice' => $json['context']['dispatcher']['stores']['QuoteSummaryStore']['financialData']['targetLowPrice']['raw'],
        ]
    ),
];

$facade = (new FinanceYahooFacade(
    new FinanceYahooConfig(),
    new CompanyCrawlerFactory(HttpClient::create())
));

$companies = $facade->crawlStock(...$siteCrawlers);

dump($companies);
