#!/usr/local/bin/php
<?php

declare(strict_types=1);

use Chemaclass\FinanceYahoo\Company\CompanyCrawlerFactory;
use Chemaclass\FinanceYahoo\Crawler\JsonExtractor\CompanyNameJsonExtractor;
use Chemaclass\FinanceYahoo\Crawler\JsonExtractor\NewsJsonExtractor;
use Chemaclass\FinanceYahoo\Crawler\JsonExtractor\PriceJsonExtractor;
use Chemaclass\FinanceYahoo\Crawler\JsonExtractor\RecommendationTrendJsonExtractor;
use Chemaclass\FinanceYahoo\Crawler\RootAppJsonCrawler;
use Chemaclass\FinanceYahoo\FinanceYahooConfig;
use Chemaclass\FinanceYahoo\FinanceYahooFacade;
use Symfony\Component\HttpClient\HttpClient;

require_once dirname(__DIR__) . '/vendor/autoload.php';

Dotenv\Dotenv::createImmutable(__DIR__)->load();

$facade = new FinanceYahooFacade(
    new FinanceYahooConfig($_ENV['TICKERS']),
    new CompanyCrawlerFactory(HttpClient::create())
);

$siteCrawler = new RootAppJsonCrawler(
    new CompanyNameJsonExtractor(),
    new PriceJsonExtractor(),
    new RecommendationTrendJsonExtractor(),
    new NewsJsonExtractor(),
);

$companies = $facade->crawlStock($siteCrawler);

// You can now do whatever you want with the crawled data :)

dump($companies);

print '-----------------------------------' . PHP_EOL;
$summary = reset($companies)->summary();
print 'name: ' . $summary[CompanyNameJsonExtractor::name()] . PHP_EOL;
print 'news: ' . json_encode($summary[NewsJsonExtractor::name()]->asArray()) . PHP_EOL;
